import type { AgentDefinition } from "./types";

export const agentRegistry = [
  {
    agent_id: "founder-cockpit",
    name: "Founder Cockpit Agent",
    department: "strategy",
    mission: "Zeigt Agent Runs, offene Freigaben, Datenqualitaet, regionale Abdeckung, Kosten, Fehler und naechste Wachstumshebel.",
    allowed_tools: ["database_read"],
    autonomy_level: "read_only",
    risk_level: "low",
    requires_approval_for: ["bulk_update", "delete_data", "start_paid_api"],
    default_output: "report",
    cost_center: "strategy",
    enabled: true,
  },
  {
    agent_id: "regional-coverage-agent",
    name: "Regional Coverage Agent",
    department: "regional_coverage",
    mission: "Bewertet Region, Gewerk und Abdeckungsgrad und erzeugt priorisierte Rechercheaufgaben.",
    allowed_tools: ["database_read", "database_write_internal", "classifier"],
    autonomy_level: "write_internal",
    risk_level: "medium",
    requires_approval_for: ["bulk_update", "publish_company", "start_paid_api"],
    default_output: "coverage_snapshot",
    cost_center: "coverage",
    enabled: true,
  },
  {
    agent_id: "company-discovery-agent",
    name: "Company Discovery Agent",
    department: "discovery",
    mission: "Findet potenzielle Betriebe aus zulaessigen Quellen und speichert Kandidaten zunaechst nur zur Pruefung.",
    allowed_tools: ["database_read", "database_write_internal", "web_search", "classifier"],
    autonomy_level: "write_internal",
    risk_level: "high",
    requires_approval_for: ["bulk_update", "publish_company", "start_paid_api"],
    default_output: "candidate_review",
    cost_center: "discovery",
    enabled: true,
  },
  {
    agent_id: "municipality-discovery-agent",
    name: "Municipality Discovery Agent",
    department: "municipality_discovery",
    mission:
      "Bearbeitet eine Gemeinde als kontrollierten Agentenauftrag: Kandidaten klassifizieren, Review/Freigaben erzeugen und begrenzte unbestaetigte Basis-Eintraege anlegen.",
    allowed_tools: ["database_read", "database_write_internal", "web_search", "website_fetch", "classifier", "outbox"],
    autonomy_level: "write_internal",
    risk_level: "high",
    requires_approval_for: ["publish_company", "send_email", "bulk_update", "delete_data", "start_paid_api"],
    default_output: "candidate_review",
    cost_center: "municipality_discovery",
    enabled: true,
  },
  {
    agent_id: "company-enrichment-agent",
    name: "Company Enrichment Agent",
    department: "enrichment",
    mission: "Analysiert offizielle Firmenwebsites, Impressum, Kontakt- und Leistungsseiten fuer hochwertige Profile.",
    allowed_tools: ["database_read", "database_write_internal", "web_search", "website_fetch", "classifier"],
    autonomy_level: "write_internal",
    risk_level: "high",
    requires_approval_for: ["overwrite_company_data", "publish_company", "bulk_update", "start_paid_api"],
    default_output: "candidate_review",
    cost_center: "enrichment",
    enabled: true,
  },
  {
    agent_id: "trade-classification-agent",
    name: "Trade Classification Agent",
    department: "classification",
    mission: "Ordnet Firmen passenden Gewerken zu und schreibt unsichere Zuordnungen in Review.",
    allowed_tools: ["database_read", "database_write_internal", "classifier"],
    autonomy_level: "write_internal",
    risk_level: "medium",
    requires_approval_for: ["overwrite_company_data", "bulk_update"],
    default_output: "classification_review",
    cost_center: "classification",
    enabled: true,
  },
  {
    agent_id: "data-quality-agent",
    name: "Data Quality Agent",
    department: "quality",
    mission: "Findet Dubletten, Konflikte und unvollstaendige Eintraege und erstellt Review-Vorschlaege.",
    allowed_tools: ["database_read", "database_write_internal", "classifier"],
    autonomy_level: "write_internal",
    risk_level: "medium",
    requires_approval_for: ["delete_data", "overwrite_company_data", "bulk_update"],
    default_output: "task_list",
    cost_center: "quality",
    enabled: true,
  },
  {
    agent_id: "verification-agent",
    name: "Verification Agent",
    department: "verification",
    mission: "Bereitet Claim- und Verifizierungsvorschlaege vor, ohne Status automatisch zu aendern.",
    allowed_tools: ["database_read", "database_write_internal", "classifier"],
    autonomy_level: "draft",
    risk_level: "high",
    requires_approval_for: ["change_verification_status", "change_claim_status", "overwrite_company_data"],
    default_output: "approval_request",
    cost_center: "verification",
    enabled: true,
  },
  {
    agent_id: "outreach-agent",
    name: "Outreach Agent",
    department: "outreach",
    mission: "Erstellt persoenliche Nachrichtenentwuerfe an Betriebe, ohne E-Mails automatisch zu senden.",
    allowed_tools: ["database_read", "database_write_internal", "outbox"],
    autonomy_level: "draft",
    risk_level: "high",
    requires_approval_for: ["send_email", "bulk_update"],
    default_output: "outbox_draft",
    cost_center: "outreach",
    enabled: true,
  },
  {
    agent_id: "seo-content-agent",
    name: "SEO Content Agent",
    department: "seo_content",
    mission: "Erstellt regionale Landingpage- und Gewerkeseiten-Entwuerfe fuer Review.",
    allowed_tools: ["database_read", "database_write_internal", "classifier"],
    autonomy_level: "draft",
    risk_level: "medium",
    requires_approval_for: ["publish_seo_page"],
    default_output: "candidate_review",
    cost_center: "seo",
    enabled: true,
  },
  {
    agent_id: "matching-agent",
    name: "Matching Agent",
    department: "matching",
    mission: "Bereitet spaeter Matching-Vorschlaege zwischen Suchenden und Betrieben vor.",
    allowed_tools: ["database_read", "classifier"],
    autonomy_level: "read_only",
    risk_level: "medium",
    requires_approval_for: ["send_email", "publish_company"],
    default_output: "report",
    cost_center: "matching",
    enabled: false,
  },
  {
    agent_id: "compliance-guard-agent",
    name: "Compliance Guard Agent",
    department: "compliance",
    mission: "Prueft Agentenaktionen auf DSGVO, Quellenlage, Sichtbarkeit, Toolrisiken und Freigaben.",
    allowed_tools: ["database_read", "classifier"],
    autonomy_level: "read_only",
    risk_level: "critical",
    requires_approval_for: ["bulk_update", "delete_data", "start_paid_api", "send_email"],
    default_output: "approval_request",
    cost_center: "compliance",
    enabled: true,
  },
  {
    agent_id: "agent-cost-controller",
    name: "Agent Cost Controller",
    department: "finance",
    mission: "Erfasst und begrenzt Token-, API- und Toolkosten pro Agent, Region und Aufgabe.",
    allowed_tools: ["database_read", "database_write_internal"],
    autonomy_level: "write_internal",
    risk_level: "medium",
    requires_approval_for: ["start_paid_api"],
    default_output: "cost_report",
    cost_center: "finance",
    enabled: true,
  },
] as const satisfies readonly AgentDefinition[];

export type AgentId = (typeof agentRegistry)[number]["agent_id"];

export function getAgentDefinition(agentId: string) {
  return agentRegistry.find((agent) => agent.agent_id === agentId) || null;
}
